#:schema https://www.schemastore.org/treefmt.json

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md", "*.ts", "*.tsx", "*.css", "*.json", "*.yaml"]
excludes = ["pnpm-lock.yaml", "node_modules/**", ".output/**", ".nitro/**", "dist/**"]
